[cite_start]name: 'lab2_pipeline' [cite: 124]
version: '1.0.0'
config-version: 2

# Update this to match what you wrote in profiles.yml
[cite_start]profile: 'playstore_profile' [cite: 132, 136]

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analysis"]

models:
  lab2_pipeline:
    # Logic to separate staging (views) from marts (tables) [cite: 138]
    staging:
      [cite_start]+materialized: view [cite: 138, 140]
    marts:
      [cite_start]+materialized: table [cite: 138]
