[cite_start]name: 'lab2_pipeline' # Matches your lab project name [cite: 124]
version: '1.0.0'
config-version: 2

# This must match the profile name in your local profiles.yml file [cite: 132]
profile: 'lab2_profile' 

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analysis"]

models:
  lab2_pipeline:
    # Set default materializations for clear layer separation [cite: 138]
    staging:
      [cite_start]+materialized: view      # Staging models will be built as views [cite: 138]
    marts:
      [cite_start]+materialized: table     # Serving tables will be built as tables [cite: 138]
